### ISSUE TITLE
첫 저장소에는 축하의 인사를 

### ISSUE THREAD

**Issue by redbean** [linearhalo/EulerPrj#1]
축하축하 축~~

근데 1번에서

if (i)%15==0:
        mins+=i
는 뭔가요? 
궁금궁금열매

**Comment by linearhalo** [comment]
3과 5의 곱을 더한 수에서 공배수인 15의 곱(중복되는 값)을 빼기 위한 거예요!

**Comment by redbean** [comment]
아하 그렇군요 ㅎㅎ
화이팅이예요~!! 5번문제 풀고 올릴꺼임 ㅡㅡ++

**Comment by redbean** [comment]
이런식으로 이슈가 종료되면 이 이슈를 클로즈 시키게 되요
클로즈 시킬께용~!

**Comment by linearhalo** [comment]
전 5번문제 풀기만 하고 코드를 안 짜서(...)올릴 수가 없네요 ㅋㅋ 코드 짜 봐야 하는데 저는 이미 누워버렸고...오늘치 집중력 다 쓴 것 같고....

**Comment by redbean** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 화이팅~!!!
